services:
  - docker

language: python
python:
  - "3.8"

before_install:
  - docker build -t shnupta/seemyfeels .

install: pip --version # prevents travis from trying to install requirements.txt

jobs:
  include:
    - stage: test
      script: docker run -it --entrypoint=/bin/bash shnupta/seemyfeels -c 'python3 test/test.py'
    - stage: deploy
      script: echo A fake deploy!!
