services:
- docker

language: python
python:
- '3.8'

install: pip --version

jobs:
  include:
  - stage: test
    before_install: docker build -t shnupta/seemyfeels .
    script: docker run -it --entrypoint=/bin/bash shnupta/seemyfeels -c 'python3 test/test.py'
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: o+NP/rb1UR6pjfZO9QqCWziIPDx8sl6F+tV+v5mT2DCfNsQSa4ILN56iQPuQjSipnIDf0AUMoWExvoCdehYccw2NUseTNcyv0PyDnTOF/53fnOuzRK9/GZrgX6e71a/mnQ+/rhDXe0zwTmTLMp2o+aYjvl0ve7yz+F3hJoGBsYJ2aSwCSVBVla57gpv4QS1OyrEudVo+upYhEGDGebv5QMmn34pxfgV41yt4/xGJO8hgGMlahZhhAkE3imPlTVT5IPzQ7O8psPaPLJcG/rObrdXxLwX1lUBVv5+CEes2XmmMF3254YDRwKtPgaJPfs2yGNfEQnc9t95c3UjriF9igseHte46m5kwd3sozEvS2XKjIQNw7iqYW8ToXtKP/O5jiIuAg9UscmnlgMWOY+Vajv5MaX5KBsfi57t0GJ6NJNKP1h30MSZykZDdolZa0tE8dxzqjiGklVTMpctCofOYxtZIfl5owjlk5Gpq/2ZEY64pfijTvc3m1wA3DSRsfTFxNlKOofeAMBI7UKlRs+K6Riw8W5nE1/sH4HQJPzzH+D0AoWb+b8U0N01KnuWmfcb/qkHjaUMbc55nG4lyxuAcPyjZqJNHJlO3ywC2gTAergI+qYUj0j+jo17mv5ye0tjXe/HU65ErAYtIiREQrLfjxe1n4Dx8DA4YdhkMLinpNeM=
      app: see-my-feels
      on:
        all_branches: true
