services:
- docker

language: python
python:
- '3.8'

install: pip --version

jobs:
  include:
  - stage: test
    before_install: docker build -t shnupta/seemyfeels .
    script: docker run -it --entrypoint=/bin/bash shnupta/seemyfeels -c 'python3 test/test.py'
  - stage: deploy
    script: skip
    deploy:
      provider: heroku
      api_key:
        secure: aTp3X1YP4+JPLIzcWRYn0HFs1uaXFDlDEx9nlID8We+qNvuLyBiVR7DyzitXuIDrVbQmjHe+npxiv4UChOmH890eJnpWXKexfrk2xj5n/NJrOyP6DrSdstFfTLWHyYDYWPRl4JYBfzrZS7dBPMnFnfYut4OSwHZbLgKQfFsdSdw3DGScb+32YopLUV5m8hLyPXdEhTNPjEqO/L8MI0qnfLXHKynGFBqUAUbCALSuKaaxNzfdomtPxqGAoGvTFszwogARc0dHmI0saLQl+WCMOEWB9PC/EhAAc5OHeZDxWeiHfMIkeFv4o9a4YXLK4Y6LDG5s5JFOSptL2h70s60Nz2Ihh0ebRH5e9oq1zfIVR13cPgXh4D/y8L9SSTum8xXg7qyK1okxdz41ZNs05desSTC6bBVc1Ly1zRJEAv3pd5eszgqmfbj+QqbX+SyFzZQjAEw/Wa4E7C+sWinGYeOdhDKFei03DAaK01naxRZz3hsH4k6m8F0m8uYzSyoRGM/7hUXtby+8kJz3HRiOKOputeVzemdj8pUi3WoP72uiPjovYMpyGP+VNZRlE4WS4IZFOfiTKBNDY1uADlwo2xICLTt2FXtFjVOOzOStytI6Fh8q4BPw5Kkh8vc3fe4ltqVae9uFzZuIvKeKM38sqa5viPlU9Uyt9lz5RD+BgMMpykA=
      app: see-my-feels
      on:
        all_branches: true
